-- =========================================================================
-- BIBI APP - DATABASE SCHEMA DDL
-- Execute this script in your Supabase SQL Editor (https://supabase.com)
-- =========================================================================

-- Enable UUID extension if not already enabled
create extension if not exists "uuid-ossp";

-- 1. Create profiles table (maps to auth.users)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text not null unique,
  name text,
  phone text,
  role text not null default 'member' check (role in ('admin', 'member', 'guest')),
  tier text not null default 'bronze' check (tier in ('bronze', 'silver', 'gold', 'platinum')),
  points integer not null default 0,
  created_at timestamp with time zone default now()
);

-- Enable RLS on profiles
alter table public.profiles enable row level security;

-- 2. Create products table
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  code text not null unique,
  tittle text not null, -- Notice typo 'tittle' matching existing frontend code
  category text not null,
  brand text,
  price numeric not null,
  stock integer not null default 0,
  image text,
  created_at timestamp with time zone default now()
);

-- Enable RLS on products
alter table public.products enable row level security;

-- 3. Create orders table
create table if not exists public.orders (
  id uuid default gen_random_uuid() primary key,
  customer_id uuid references public.profiles(id) on delete cascade not null,
  order_date timestamp with time zone default now(),
  total_amount numeric not null,
  discount_amount numeric not null default 0,
  final_amount numeric not null,
  points_earned integer not null default 0,
  status text not null default 'Pending' check (status in ('Pending', 'Delivered', 'Canceled')),
  created_at timestamp with time zone default now()
);

-- Enable RLS on orders
alter table public.orders enable row level security;

-- 4. Create order_items table
create table if not exists public.order_items (
  id uuid default gen_random_uuid() primary key,
  order_id uuid references public.orders(id) on delete cascade not null,
  product_id bigint references public.products(id) on delete restrict not null,
  quantity integer not null check (quantity > 0),
  price numeric not null
);

-- Enable RLS on order_items
alter table public.order_items enable row level security;


-- =========================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =========================================================================

-- Profiles Policies
create policy "Users can view own profile" on public.profiles
  for select using (auth.uid() = id);

create policy "Admins can view all profiles" on public.profiles
  for select using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

create policy "Users can update own basic profile" on public.profiles
  for update using (auth.uid() = id);

create policy "Admins can update any profile" on public.profiles
  for update using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

-- Products Policies
create policy "Anyone can select products" on public.products
  for select using (auth.role() = 'authenticated');

create policy "Admins can manage products" on public.products
  for all using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

-- Orders Policies
create policy "Users can view own orders" on public.orders
  for select using (customer_id = auth.uid());

create policy "Admins can view all orders" on public.orders
  for select using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

create policy "Users can insert own orders" on public.orders
  for insert with check (customer_id = auth.uid());

create policy "Admins can update order status" on public.orders
  for update using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

-- Order Items Policies
create policy "Users can view own order items" on public.order_items
  for select using (
    exists (select 1 from public.orders where id = order_items.order_id and customer_id = auth.uid())
  );

create policy "Admins can view all order items" on public.order_items
  for select using (
    exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
  );

create policy "Users can insert own order items" on public.order_items
  for insert with check (
    exists (select 1 from public.orders where id = order_items.order_id and customer_id = auth.uid())
  );


-- =========================================================================
-- TRIGGERS & FUNCTIONS
-- =========================================================================

-- Trigger to automatically create profile on sign up
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, name, role, tier, points)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    'member',
    'bronze',
    0
  );
  return new;
end;
$$ language plpgsql security definer;

-- Drop trigger if it exists
drop trigger if exists on_auth_user_created on auth.users;

-- Create the trigger
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- =========================================================================
-- SEED DATA (PRODUCTS)
-- =========================================================================

insert into public.products (code, tittle, category, brand, price, stock, image) values
('BEA-001', 'Essence Mascara Lash Princess', 'beauty', 'Essence', 9990, 50, 'https://dummyimage.com/150/009262/fff&text=Mascara'),
('BEA-002', 'Eyeshadow Palette with Mirror', 'beauty', 'Glamour', 150000, 25, 'https://dummyimage.com/150/009262/fff&text=Eyeshadow'),
('BEA-003', 'Powder Canister', 'beauty', 'Silky', 85000, 30, 'https://dummyimage.com/150/009262/fff&text=Powder'),
('BEA-004', 'Red Lipstick', 'beauty', 'MatteLook', 75000, 40, 'https://dummyimage.com/150/009262/fff&text=Lipstick'),
('BEA-005', 'Liquid Foundation', 'beauty', 'CoverAll', 120000, 20, 'https://dummyimage.com/150/009262/fff&text=Foundation'),
('BEA-006', 'Eyeliner Pen Black', 'beauty', 'SharpEye', 45000, 60, 'https://dummyimage.com/150/009262/fff&text=Eyeliner'),
('BEA-007', 'Blush On Peach', 'beauty', 'GlowUp', 65000, 15, 'https://dummyimage.com/150/009262/fff&text=Blush'),
('BEA-008', 'Face Primer', 'beauty', 'SmoothBase', 110000, 10, 'https://dummyimage.com/150/009262/fff&text=Primer'),
('BEA-009', 'Setting Spray', 'beauty', 'StayLong', 95000, 35, 'https://dummyimage.com/150/009262/fff&text=Spray'),
('BEA-010', 'Concealer High Cover', 'beauty', 'HideIt', 80000, 22, 'https://dummyimage.com/150/009262/fff&text=Concealer')
on conflict (code) do nothing;
